export default {
    'code': 0,
    'level': null,
    'msg': '操作成功',
    'ok': true,
    'data': {
        'employeeId': 1,
        'userType': 'ADMIN_EMPLOYEE',
        'loginName': 'admin',
        'actualName': '管理员',
        'avatar':
            'http://172.20.0.1:1024/upload/public/common/1eea469452484ffea4a42570c4072466_20240702220447.jpg',
        'gender': 0,
        'phone': '13500000000',
        'departmentId': 1,
        'departmentName': '1024创新实验室',
        'disabledFlag': false,
        'administratorFlag': true,
        'remark': null,
        'ip': null,
        'userAgent': null,
        'token': '0aa29ca6ed374541847b5057eb9c0a9d',
        'menuList': [
            {
                'menuName': '删除',
                'menuType': 3,
                'parentId': 26,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'system:menu:batchDelete',
                'apiPerms': 'system:menu:batchDelete',
                'icon': null,
                'contextMenuId': 26,
                'menuId': 40,
                'createTime': '2021-08-12 09:45:56',
                'createUserId': 1,
                'updateTime': '2023-10-07 18:15:50',
                'updateUserId': 1,
            },
            {
                'menuName': '组件演示',
                'menuType': 2,
                'parentId': 84,
                'sort': null,
                'path': '/demonstration/index',
                'component': '/support/demonstration/index.vue',
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': null,
                'webPerms': null,
                'apiPerms': null,
                'icon': 'ClearOutlined',
                'contextMenuId': null,
                'menuId': 85,
                'createTime': '2022-05-20 23:16:46',
                'createUserId': 1,
                'updateTime': '2022-05-20 23:16:46',
                'updateUserId': null,
            },
            {
                'menuName': '添加员工',
                'menuType': 3,
                'parentId': 46,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'system:employee:add',
                'apiPerms': 'system:employee:add',
                'icon': null,
                'contextMenuId': null,
                'menuId': 91,
                'createTime': '2022-05-27 00:11:38',
                'createUserId': 1,
                'updateTime': '2023-10-07 18:27:46',
                'updateUserId': 1,
            },
            {
                'menuName': '编辑员工',
                'menuType': 3,
                'parentId': 46,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'system:employee:update',
                'apiPerms': 'system:employee:update',
                'icon': null,
                'contextMenuId': null,
                'menuId': 92,
                'createTime': '2022-05-27 00:12:10',
                'createUserId': 1,
                'updateTime': '2023-10-07 18:27:49',
                'updateUserId': 1,
            },
            {
                'menuName': '禁用启用员工',
                'menuType': 3,
                'parentId': 46,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'system:employee:disabled',
                'apiPerms': 'system:employee:disabled',
                'icon': null,
                'contextMenuId': null,
                'menuId': 93,
                'createTime': '2022-05-27 00:12:37',
                'createUserId': 1,
                'updateTime': '2023-10-07 18:27:53',
                'updateUserId': 1,
            },
            {
                'menuName': '调整员工部门',
                'menuType': 3,
                'parentId': 46,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'system:employee:department:update',
                'apiPerms': 'system:employee:department:update',
                'icon': null,
                'contextMenuId': null,
                'menuId': 94,
                'createTime': '2022-05-27 00:12:59',
                'createUserId': 1,
                'updateTime': '2023-10-07 18:27:34',
                'updateUserId': 1,
            },
            {
                'menuName': '重置密码',
                'menuType': 3,
                'parentId': 46,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'system:employee:password:reset',
                'apiPerms': 'system:employee:password:reset',
                'icon': null,
                'contextMenuId': null,
                'menuId': 95,
                'createTime': '2022-05-27 00:13:30',
                'createUserId': 1,
                'updateTime': '2023-10-07 18:27:57',
                'updateUserId': 1,
            },
            {
                'menuName': '删除员工',
                'menuType': 3,
                'parentId': 46,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'system:employee:delete',
                'apiPerms': 'system:employee:delete',
                'icon': null,
                'contextMenuId': null,
                'menuId': 96,
                'createTime': '2022-05-27 00:14:08',
                'createUserId': 1,
                'updateTime': '2023-10-07 18:28:01',
                'updateUserId': 1,
            },
            {
                'menuName': '添加角色',
                'menuType': 3,
                'parentId': 76,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'system:role:add',
                'apiPerms': 'system:role:add',
                'icon': null,
                'contextMenuId': null,
                'menuId': 97,
                'createTime': '2022-05-27 00:34:00',
                'createUserId': 1,
                'updateTime': '2023-10-07 18:42:31',
                'updateUserId': 1,
            },
            {
                'menuName': '删除角色',
                'menuType': 3,
                'parentId': 76,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'system:role:delete',
                'apiPerms': 'system:role:delete',
                'icon': null,
                'contextMenuId': null,
                'menuId': 98,
                'createTime': '2022-05-27 00:34:19',
                'createUserId': 1,
                'updateTime': '2023-10-07 18:42:35',
                'updateUserId': 1,
            },
            {
                'menuName': '编辑角色',
                'menuType': 3,
                'parentId': 76,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'system:role:update',
                'apiPerms': 'system:role:update',
                'icon': null,
                'contextMenuId': null,
                'menuId': 99,
                'createTime': '2022-05-27 00:34:55',
                'createUserId': 1,
                'updateTime': '2023-10-07 18:42:44',
                'updateUserId': 1,
            },
            {
                'menuName': '更新数据范围',
                'menuType': 3,
                'parentId': 76,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'system:role:dataScope:update',
                'apiPerms': 'system:role:dataScope:update',
                'icon': null,
                'contextMenuId': null,
                'menuId': 100,
                'createTime': '2022-05-27 00:37:03',
                'createUserId': 1,
                'updateTime': '2023-10-07 18:41:49',
                'updateUserId': 1,
            },
            {
                'menuName': '批量移除员工',
                'menuType': 3,
                'parentId': 76,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'system:role:employee:batch:delete',
                'apiPerms': 'system:role:employee:batch:delete',
                'icon': null,
                'contextMenuId': null,
                'menuId': 101,
                'createTime': '2022-05-27 00:39:05',
                'createUserId': 1,
                'updateTime': '2023-10-07 18:43:32',
                'updateUserId': 1,
            },
            {
                'menuName': '移除员工',
                'menuType': 3,
                'parentId': 76,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'system:role:employee:delete',
                'apiPerms': 'system:role:employee:delete',
                'icon': null,
                'contextMenuId': null,
                'menuId': 102,
                'createTime': '2022-05-27 00:39:21',
                'createUserId': 1,
                'updateTime': '2023-10-07 18:43:37',
                'updateUserId': 1,
            },
            {
                'menuName': '添加员工',
                'menuType': 3,
                'parentId': 76,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'system:role:employee:add',
                'apiPerms': 'system:role:employee:add',
                'icon': null,
                'contextMenuId': null,
                'menuId': 103,
                'createTime': '2022-05-27 00:39:38',
                'createUserId': 1,
                'updateTime': '2023-10-07 18:44:05',
                'updateUserId': 1,
            },
            {
                'menuName': '修改权限',
                'menuType': 3,
                'parentId': 76,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'system:role:menu:update',
                'apiPerms': 'system:role:menu:update',
                'icon': null,
                'contextMenuId': null,
                'menuId': 104,
                'createTime': '2022-05-27 00:41:55',
                'createUserId': 1,
                'updateTime': '2023-10-07 18:44:11',
                'updateUserId': 1,
            },
            {
                'menuName': '添加',
                'menuType': 3,
                'parentId': 26,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'system:menu:add',
                'apiPerms': 'system:menu:add',
                'icon': null,
                'contextMenuId': 26,
                'menuId': 105,
                'createTime': '2022-05-27 00:44:37',
                'createUserId': 1,
                'updateTime': '2023-10-07 17:35:35',
                'updateUserId': 1,
            },
            {
                'menuName': '编辑',
                'menuType': 3,
                'parentId': 26,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'system:menu:update',
                'apiPerms': 'system:menu:update',
                'icon': null,
                'contextMenuId': 26,
                'menuId': 106,
                'createTime': '2022-05-27 00:44:59',
                'createUserId': 1,
                'updateTime': '2023-10-07 17:35:48',
                'updateUserId': 1,
            },
            {
                'menuName': '查询',
                'menuType': 3,
                'parentId': 112,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': null,
                'webPerms': 'ad',
                'apiPerms': null,
                'icon': null,
                'contextMenuId': null,
                'menuId': 113,
                'createTime': '2022-06-17 11:31:36',
                'createUserId': 1,
                'updateTime': '2022-06-17 11:31:36',
                'updateUserId': null,
            },
            {
                'menuName': '公告详情',
                'menuType': 2,
                'parentId': 132,
                'sort': null,
                'path': '/oa/notice/notice-detail',
                'component': '/business/oa/notice/notice-detail.vue',
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': false,
                'disabledFlag': false,
                'permsType': null,
                'webPerms': null,
                'apiPerms': null,
                'icon': null,
                'contextMenuId': null,
                'menuId': 142,
                'createTime': '2022-06-25 16:38:47',
                'createUserId': 1,
                'updateTime': '2022-09-14 19:46:17',
                'updateUserId': 1,
            },
            {
                'menuName': '企业详情',
                'menuType': 2,
                'parentId': 138,
                'sort': null,
                'path': '/oa/enterprise/enterprise-detail',
                'component': '/business/oa/enterprise/enterprise-detail.vue',
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': false,
                'disabledFlag': false,
                'permsType': null,
                'webPerms': null,
                'apiPerms': null,
                'icon': null,
                'contextMenuId': null,
                'menuId': 145,
                'createTime': '2022-09-14 18:52:52',
                'createUserId': 1,
                'updateTime': '2022-11-22 10:39:07',
                'updateUserId': 1,
            },
            {
                'menuName': '我的通知',
                'menuType': 2,
                'parentId': 132,
                'sort': null,
                'path': '/oa/notice/notice-employee-list',
                'component': '/business/oa/notice/notice-employee-list.vue',
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': false,
                'disabledFlag': false,
                'permsType': null,
                'webPerms': null,
                'apiPerms': null,
                'icon': null,
                'contextMenuId': null,
                'menuId': 149,
                'createTime': '2022-09-14 20:29:41',
                'createUserId': 1,
                'updateTime': '2022-09-14 20:31:23',
                'updateUserId': 1,
            },
            {
                'menuName': '我的通知公告详情',
                'menuType': 2,
                'parentId': 132,
                'sort': null,
                'path': '/oa/notice/notice-employee-detail',
                'component': '/business/oa/notice/notice-employee-detail.vue',
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': false,
                'disabledFlag': false,
                'permsType': null,
                'webPerms': null,
                'apiPerms': null,
                'icon': null,
                'contextMenuId': null,
                'menuId': 150,
                'createTime': '2022-09-14 20:30:25',
                'createUserId': 1,
                'updateTime': '2022-09-14 20:31:38',
                'updateUserId': 1,
            },
            {
                'menuName': '清除缓存',
                'menuType': 3,
                'parentId': 133,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': true,
                'permsType': 1,
                'webPerms': 'support:cache:delete',
                'apiPerms': 'support:cache:delete',
                'icon': null,
                'contextMenuId': 133,
                'menuId': 153,
                'createTime': '2022-10-15 22:45:13',
                'createUserId': 1,
                'updateTime': '2023-10-07 16:22:29',
                'updateUserId': 1,
            },
            {
                'menuName': '获取缓存key',
                'menuType': 3,
                'parentId': 133,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': true,
                'permsType': 1,
                'webPerms': 'support:cache:keys',
                'apiPerms': 'support:cache:keys',
                'icon': null,
                'contextMenuId': 133,
                'menuId': 154,
                'createTime': '2022-10-15 22:45:48',
                'createUserId': 1,
                'updateTime': '2023-10-07 16:22:35',
                'updateUserId': 1,
            },
            {
                'menuName': '查看结果',
                'menuType': 3,
                'parentId': 117,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'support:reload:result',
                'apiPerms': 'support:reload:result',
                'icon': null,
                'contextMenuId': 117,
                'menuId': 156,
                'createTime': '2022-10-15 23:17:23',
                'createUserId': 1,
                'updateTime': '2023-10-07 14:31:47',
                'updateUserId': 1,
            },
            {
                'menuName': '单号生成',
                'menuType': 3,
                'parentId': 130,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'support:serialNumber:generate',
                'apiPerms': 'support:serialNumber:generate',
                'icon': null,
                'contextMenuId': 130,
                'menuId': 157,
                'createTime': '2022-10-15 23:21:06',
                'createUserId': 1,
                'updateTime': '2023-10-07 18:22:46',
                'updateUserId': 1,
            },
            {
                'menuName': '生成记录',
                'menuType': 3,
                'parentId': 130,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'support:serialNumber:record',
                'apiPerms': 'support:serialNumber:record',
                'icon': null,
                'contextMenuId': 130,
                'menuId': 158,
                'createTime': '2022-10-15 23:21:34',
                'createUserId': 1,
                'updateTime': '2023-10-07 18:22:55',
                'updateUserId': 1,
            },
            {
                'menuName': '新建',
                'menuType': 3,
                'parentId': 110,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'support:dict:add',
                'apiPerms': 'support:dict:add',
                'icon': null,
                'contextMenuId': 110,
                'menuId': 159,
                'createTime': '2022-10-15 23:23:51',
                'createUserId': 1,
                'updateTime': '2023-10-07 18:18:24',
                'updateUserId': 1,
            },
            {
                'menuName': '编辑',
                'menuType': 3,
                'parentId': 110,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'support:dict:edit',
                'apiPerms': 'support:dict:edit',
                'icon': null,
                'contextMenuId': 110,
                'menuId': 160,
                'createTime': '2022-10-15 23:24:05',
                'createUserId': 1,
                'updateTime': '2023-10-07 18:19:17',
                'updateUserId': 1,
            },
            {
                'menuName': '批量删除',
                'menuType': 3,
                'parentId': 110,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'support:dict:delete',
                'apiPerms': 'support:dict:delete',
                'icon': null,
                'contextMenuId': 110,
                'menuId': 161,
                'createTime': '2022-10-15 23:24:34',
                'createUserId': 1,
                'updateTime': '2023-10-07 18:19:39',
                'updateUserId': 1,
            },
            {
                'menuName': '刷新缓存',
                'menuType': 3,
                'parentId': 110,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'support:dict:refresh',
                'apiPerms': 'support:dict:refresh',
                'icon': null,
                'contextMenuId': 110,
                'menuId': 162,
                'createTime': '2022-10-15 23:24:55',
                'createUserId': 1,
                'updateTime': '2023-10-07 18:18:37',
                'updateUserId': 1,
            },
            {
                'menuName': '新建',
                'menuType': 3,
                'parentId': 109,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'support:config:add',
                'apiPerms': 'support:config:add',
                'icon': null,
                'contextMenuId': 109,
                'menuId': 163,
                'createTime': '2022-10-15 23:26:56',
                'createUserId': 1,
                'updateTime': '2023-10-07 18:16:17',
                'updateUserId': 1,
            },
            {
                'menuName': '编辑',
                'menuType': 3,
                'parentId': 109,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'support:config:update',
                'apiPerms': 'support:config:update',
                'icon': null,
                'contextMenuId': 109,
                'menuId': 164,
                'createTime': '2022-10-15 23:27:07',
                'createUserId': 1,
                'updateTime': '2023-10-07 18:16:24',
                'updateUserId': 1,
            },
            {
                'menuName': '查询',
                'menuType': 3,
                'parentId': 47,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'goods:query',
                'apiPerms': 'goods:query',
                'icon': null,
                'contextMenuId': 47,
                'menuId': 165,
                'createTime': '2022-10-16 19:55:39',
                'createUserId': 1,
                'updateTime': '2023-10-07 13:58:28',
                'updateUserId': 1,
            },
            {
                'menuName': '新建',
                'menuType': 3,
                'parentId': 47,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'goods:add',
                'apiPerms': 'goods:add',
                'icon': null,
                'contextMenuId': 47,
                'menuId': 166,
                'createTime': '2022-10-16 19:56:00',
                'createUserId': 1,
                'updateTime': '2023-10-07 13:58:32',
                'updateUserId': 1,
            },
            {
                'menuName': '批量删除',
                'menuType': 3,
                'parentId': 47,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'goods:batchDelete',
                'apiPerms': 'goods:batchDelete',
                'icon': null,
                'contextMenuId': 47,
                'menuId': 167,
                'createTime': '2022-10-16 19:56:15',
                'createUserId': 1,
                'updateTime': '2023-10-07 13:58:35',
                'updateUserId': 1,
            },
            {
                'menuName': '新建',
                'menuType': 3,
                'parentId': 78,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'category:add',
                'apiPerms': 'category:add',
                'icon': null,
                'contextMenuId': 78,
                'menuId': 173,
                'createTime': '2022-10-16 20:17:02',
                'createUserId': 1,
                'updateTime': '2023-10-07 13:54:01',
                'updateUserId': 1,
            },
            {
                'menuName': '查询',
                'menuType': 3,
                'parentId': 78,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'category:tree',
                'apiPerms': 'category:tree',
                'icon': null,
                'contextMenuId': 78,
                'menuId': 174,
                'createTime': '2022-10-16 20:17:22',
                'createUserId': 1,
                'updateTime': '2023-10-07 13:54:33',
                'updateUserId': 1,
            },
            {
                'menuName': '编辑',
                'menuType': 3,
                'parentId': 78,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'category:update',
                'apiPerms': 'category:update',
                'icon': null,
                'contextMenuId': 78,
                'menuId': 175,
                'createTime': '2022-10-16 20:17:38',
                'createUserId': 1,
                'updateTime': '2023-10-07 13:54:18',
                'updateUserId': 1,
            },
            {
                'menuName': '删除',
                'menuType': 3,
                'parentId': 78,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'category:delete',
                'apiPerms': 'category:delete',
                'icon': null,
                'contextMenuId': 78,
                'menuId': 176,
                'createTime': '2022-10-16 20:17:50',
                'createUserId': 1,
                'updateTime': '2023-10-07 13:54:27',
                'updateUserId': 1,
            },
            {
                'menuName': '新建',
                'menuType': 3,
                'parentId': 79,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'custom:category:add',
                'apiPerms': 'category:add',
                'icon': null,
                'contextMenuId': 78,
                'menuId': 177,
                'createTime': '2022-10-16 20:17:02',
                'createUserId': 1,
                'updateTime': '2023-10-07 13:57:32',
                'updateUserId': 1,
            },
            {
                'menuName': '查询',
                'menuType': 3,
                'parentId': 79,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'custom:category:tree',
                'apiPerms': 'category:tree',
                'icon': null,
                'contextMenuId': 78,
                'menuId': 178,
                'createTime': '2022-10-16 20:17:22',
                'createUserId': 1,
                'updateTime': '2023-10-07 13:57:50',
                'updateUserId': 1,
            },
            {
                'menuName': '编辑',
                'menuType': 3,
                'parentId': 79,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'custom:category:update',
                'apiPerms': 'category:update',
                'icon': null,
                'contextMenuId': 78,
                'menuId': 179,
                'createTime': '2022-10-16 20:17:38',
                'createUserId': 1,
                'updateTime': '2023-10-07 13:58:02',
                'updateUserId': 1,
            },
            {
                'menuName': '删除',
                'menuType': 3,
                'parentId': 79,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'custom:category:delete',
                'apiPerms': 'category:delete',
                'icon': null,
                'contextMenuId': 78,
                'menuId': 180,
                'createTime': '2022-10-16 20:17:50',
                'createUserId': 1,
                'updateTime': '2023-10-07 13:58:12',
                'updateUserId': 1,
            },
            {
                'menuName': '查询',
                'menuType': 3,
                'parentId': 144,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'oa:enterprise:query',
                'apiPerms': 'oa:enterprise:query',
                'icon': null,
                'contextMenuId': 144,
                'menuId': 181,
                'createTime': '2022-10-16 20:25:14',
                'createUserId': 1,
                'updateTime': '2023-10-07 12:00:09',
                'updateUserId': 1,
            },
            {
                'menuName': '新建',
                'menuType': 3,
                'parentId': 144,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'oa:enterprise:add',
                'apiPerms': 'oa:enterprise:add',
                'icon': null,
                'contextMenuId': 144,
                'menuId': 182,
                'createTime': '2022-10-16 20:25:25',
                'createUserId': 1,
                'updateTime': '2023-10-07 12:00:17',
                'updateUserId': 1,
            },
            {
                'menuName': '编辑',
                'menuType': 3,
                'parentId': 144,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'oa:enterprise:update',
                'apiPerms': 'oa:enterprise:update',
                'icon': null,
                'contextMenuId': 144,
                'menuId': 183,
                'createTime': '2022-10-16 20:25:36',
                'createUserId': 1,
                'updateTime': '2023-10-07 12:00:38',
                'updateUserId': 1,
            },
            {
                'menuName': '删除',
                'menuType': 3,
                'parentId': 144,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'oa:enterprise:delete',
                'apiPerms': 'oa:enterprise:delete',
                'icon': null,
                'contextMenuId': 144,
                'menuId': 184,
                'createTime': '2022-10-16 20:25:53',
                'createUserId': 1,
                'updateTime': '2023-10-07 12:00:46',
                'updateUserId': 1,
            },
            {
                'menuName': '查询',
                'menuType': 3,
                'parentId': 132,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'oa:notice:query',
                'apiPerms': 'oa:notice:query',
                'icon': null,
                'contextMenuId': 132,
                'menuId': 185,
                'createTime': '2022-10-16 20:26:38',
                'createUserId': 1,
                'updateTime': '2023-10-07 11:43:01',
                'updateUserId': 1,
            },
            {
                'menuName': '新建',
                'menuType': 3,
                'parentId': 132,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'oa:notice:add',
                'apiPerms': 'oa:notice:add',
                'icon': null,
                'contextMenuId': 132,
                'menuId': 186,
                'createTime': '2022-10-16 20:27:04',
                'createUserId': 1,
                'updateTime': '2023-10-07 11:43:07',
                'updateUserId': 1,
            },
            {
                'menuName': '编辑',
                'menuType': 3,
                'parentId': 132,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'oa:notice:update',
                'apiPerms': 'oa:notice:update',
                'icon': null,
                'contextMenuId': 132,
                'menuId': 187,
                'createTime': '2022-10-16 20:27:15',
                'createUserId': 1,
                'updateTime': '2023-10-07 11:43:12',
                'updateUserId': 1,
            },
            {
                'menuName': '删除',
                'menuType': 3,
                'parentId': 132,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'oa:notice:delete',
                'apiPerms': 'oa:notice:delete',
                'icon': null,
                'contextMenuId': 132,
                'menuId': 188,
                'createTime': '2022-10-16 20:27:23',
                'createUserId': 1,
                'updateTime': '2023-10-07 11:43:18',
                'updateUserId': 1,
            },
            {
                'menuName': '查询',
                'menuType': 3,
                'parentId': 152,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'support:changeLog:query',
                'apiPerms': '',
                'icon': null,
                'contextMenuId': 152,
                'menuId': 190,
                'createTime': '2022-10-16 20:28:33',
                'createUserId': 1,
                'updateTime': '2023-10-07 14:25:05',
                'updateUserId': 1,
            },
            {
                'menuName': '新建',
                'menuType': 3,
                'parentId': 152,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'support:changeLog:add',
                'apiPerms': 'support:changeLog:add',
                'icon': null,
                'contextMenuId': 152,
                'menuId': 191,
                'createTime': '2022-10-16 20:28:46',
                'createUserId': 1,
                'updateTime': '2023-10-07 14:24:15',
                'updateUserId': 1,
            },
            {
                'menuName': '批量删除',
                'menuType': 3,
                'parentId': 152,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'support:changeLog:batchDelete',
                'apiPerms': 'support:changeLog:batchDelete',
                'icon': null,
                'contextMenuId': 152,
                'menuId': 192,
                'createTime': '2022-10-16 20:29:10',
                'createUserId': 1,
                'updateTime': '2023-10-07 14:24:22',
                'updateUserId': 1,
            },
            {
                'menuName': '删除',
                'menuType': 3,
                'parentId': 47,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'goods:delete',
                'apiPerms': 'goods:delete',
                'icon': null,
                'contextMenuId': 47,
                'menuId': 194,
                'createTime': '2022-10-21 20:00:12',
                'createUserId': 1,
                'updateTime': '2023-10-07 13:58:39',
                'updateUserId': 1,
            },
            {
                'menuName': '修改',
                'menuType': 3,
                'parentId': 47,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'goods:update',
                'apiPerms': 'goods:update',
                'icon': null,
                'contextMenuId': null,
                'menuId': 195,
                'createTime': '2022-10-21 20:05:23',
                'createUserId': 1,
                'updateTime': '2023-10-07 13:58:42',
                'updateUserId': 1,
            },
            {
                'menuName': '查看详情',
                'menuType': 3,
                'parentId': 145,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'oa:enterprise:detail',
                'apiPerms': 'oa:enterprise:detail',
                'icon': null,
                'contextMenuId': null,
                'menuId': 196,
                'createTime': '2022-10-21 20:16:47',
                'createUserId': 1,
                'updateTime': '2023-10-07 11:48:59',
                'updateUserId': 1,
            },
            {
                'menuName': '删除',
                'menuType': 3,
                'parentId': 152,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'support:changeLog:delete',
                'apiPerms': 'support:changeLog:delete',
                'icon': null,
                'contextMenuId': null,
                'menuId': 198,
                'createTime': '2022-10-21 20:42:34',
                'createUserId': 1,
                'updateTime': '2023-10-07 14:24:32',
                'updateUserId': 1,
            },
            {
                'menuName': '查询',
                'menuType': 3,
                'parentId': 109,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'support:config:query',
                'apiPerms': 'support:config:query',
                'icon': null,
                'contextMenuId': null,
                'menuId': 199,
                'createTime': '2022-10-21 20:45:14',
                'createUserId': 1,
                'updateTime': '2023-10-07 18:16:27',
                'updateUserId': 1,
            },
            {
                'menuName': '查询',
                'menuType': 3,
                'parentId': 193,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'support:file:query',
                'apiPerms': 'support:file:query',
                'icon': null,
                'contextMenuId': null,
                'menuId': 200,
                'createTime': '2022-10-21 20:47:23',
                'createUserId': 1,
                'updateTime': '2023-10-07 18:24:43',
                'updateUserId': 1,
            },
            {
                'menuName': '查询',
                'menuType': 3,
                'parentId': 143,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'support:loginLog:query',
                'apiPerms': 'support:loginLog:query',
                'icon': null,
                'contextMenuId': null,
                'menuId': 203,
                'createTime': '2022-10-21 21:05:11',
                'createUserId': 1,
                'updateTime': '2023-10-07 14:27:23',
                'updateUserId': 1,
            },
            {
                'menuName': '查询',
                'menuType': 3,
                'parentId': 81,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'support:operateLog:query',
                'apiPerms': 'support:operateLog:query',
                'icon': null,
                'contextMenuId': null,
                'menuId': 204,
                'createTime': '2022-10-22 10:33:31',
                'createUserId': 1,
                'updateTime': '2023-10-07 14:27:56',
                'updateUserId': 1,
            },
            {
                'menuName': '详情',
                'menuType': 3,
                'parentId': 81,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'support:operateLog:detail',
                'apiPerms': 'support:operateLog:detail',
                'icon': null,
                'contextMenuId': null,
                'menuId': 205,
                'createTime': '2022-10-22 10:33:49',
                'createUserId': 1,
                'updateTime': '2023-10-07 14:28:04',
                'updateUserId': 1,
            },
            {
                'menuName': '更新',
                'menuType': 3,
                'parentId': 152,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'support:changeLog:update',
                'apiPerms': 'support:changeLog:update',
                'icon': null,
                'contextMenuId': null,
                'menuId': 207,
                'createTime': '2022-10-22 11:51:32',
                'createUserId': 1,
                'updateTime': '2023-10-07 14:24:39',
                'updateUserId': 1,
            },
            {
                'menuName': '查询',
                'menuType': 3,
                'parentId': 117,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': true,
                'visibleFlag': true,
                'disabledFlag': true,
                'permsType': 1,
                'webPerms': 'support:reload:query',
                'apiPerms': 'support:reload:query',
                'icon': null,
                'contextMenuId': null,
                'menuId': 212,
                'createTime': '2023-10-07 14:31:36',
                'createUserId': 1,
                'updateTime': '2023-10-07 14:31:36',
                'updateUserId': null,
            },
            {
                'menuName': '导出',
                'menuType': 3,
                'parentId': 47,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': true,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'goods:exportGoods',
                'apiPerms': 'goods:exportGoods',
                'icon': null,
                'contextMenuId': null,
                'menuId': 216,
                'createTime': '2023-12-01 19:34:03',
                'createUserId': 1,
                'updateTime': '2023-12-01 19:34:03',
                'updateUserId': null,
            },
            {
                'menuName': '查询任务',
                'menuType': 3,
                'parentId': 221,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': true,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'support:job:query',
                'apiPerms': 'support:job:query',
                'icon': null,
                'contextMenuId': 221,
                'menuId': 229,
                'createTime': '2024-06-29 11:14:15',
                'createUserId': 2,
                'updateTime': '2024-06-29 11:15:00',
                'updateUserId': 2,
            },
            {
                'menuName': '更新任务',
                'menuType': 3,
                'parentId': 221,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': true,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'support:job:update',
                'apiPerms': 'support:job:update',
                'icon': null,
                'contextMenuId': 221,
                'menuId': 230,
                'createTime': '2024-06-29 11:15:40',
                'createUserId': 2,
                'updateTime': '2024-06-29 11:15:40',
                'updateUserId': null,
            },
            {
                'menuName': '执行任务',
                'menuType': 3,
                'parentId': 221,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': true,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'support:job:execute',
                'apiPerms': 'support:job:execute',
                'icon': null,
                'contextMenuId': 221,
                'menuId': 231,
                'createTime': '2024-06-29 11:16:03',
                'createUserId': 2,
                'updateTime': '2024-06-29 11:16:03',
                'updateUserId': null,
            },
            {
                'menuName': '查询记录',
                'menuType': 3,
                'parentId': 221,
                'sort': null,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': true,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'support:job:log:query',
                'apiPerms': 'support:job:log:query',
                'icon': null,
                'contextMenuId': 221,
                'menuId': 232,
                'createTime': '2024-06-29 11:16:37',
                'createUserId': 2,
                'updateTime': '2024-06-29 11:16:37',
                'updateUserId': null,
            },
            {
                'menuName': '菜单管理',
                'menuType': 2,
                'parentId': 50,
                'sort': 1,
                'path': '/menu/list',
                'component': '/system/menu/menu-list.vue',
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': true,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': null,
                'webPerms': null,
                'apiPerms': null,
                'icon': 'CopyOutlined',
                'contextMenuId': null,
                'menuId': 26,
                'createTime': '2021-08-09 15:04:35',
                'createUserId': 2,
                'updateTime': '2023-12-01 19:39:03',
                'updateUserId': 1,
            },
            {
                'menuName': '商品管理',
                'menuType': 2,
                'parentId': 48,
                'sort': 1,
                'path': '/erp/goods/list',
                'component': '/business/erp/goods/goods-list.vue',
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': true,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': null,
                'webPerms': null,
                'apiPerms': null,
                'icon': 'AliwangwangOutlined',
                'contextMenuId': null,
                'menuId': 47,
                'createTime': '2021-08-12 17:58:39',
                'createUserId': 1,
                'updateTime': '2023-12-01 19:33:08',
                'updateUserId': 1,
            },
            {
                'menuName': '添加部门',
                'menuType': 3,
                'parentId': 46,
                'sort': 1,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'system:department:add',
                'apiPerms': 'system:department:add',
                'icon': null,
                'contextMenuId': null,
                'menuId': 86,
                'createTime': '2022-05-26 23:33:37',
                'createUserId': 1,
                'updateTime': '2023-10-07 18:26:35',
                'updateUserId': 1,
            },
            {
                'menuName': '功能Demo',
                'menuType': 1,
                'parentId': 0,
                'sort': 1,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': null,
                'webPerms': null,
                'apiPerms': null,
                'icon': 'BankOutlined',
                'contextMenuId': null,
                'menuId': 138,
                'createTime': '2022-06-24 20:09:18',
                'createUserId': 1,
                'updateTime': '2024-07-08 13:46:54',
                'updateUserId': 1,
            },
            {
                'menuName': '企业管理',
                'menuType': 2,
                'parentId': 138,
                'sort': 1,
                'path': '/oa/enterprise/enterprise-list',
                'component': '/business/oa/enterprise/enterprise-list.vue',
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': null,
                'webPerms': null,
                'apiPerms': null,
                'icon': 'ShopOutlined',
                'contextMenuId': null,
                'menuId': 144,
                'createTime': '2022-09-14 17:00:07',
                'createUserId': 1,
                'updateTime': '2024-07-08 13:48:24',
                'updateUserId': 1,
            },
            {
                'menuName': '帮助文档',
                'menuType': 2,
                'parentId': 218,
                'sort': 1,
                'path': '/help-doc/help-doc-manage-list',
                'component':
                    '/support/help-doc/management/help-doc-manage-list.vue',
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': null,
                'webPerms': null,
                'apiPerms': null,
                'icon': 'FolderViewOutlined',
                'contextMenuId': null,
                'menuId': 147,
                'createTime': '2022-09-14 19:59:01',
                'createUserId': 1,
                'updateTime': '2023-12-01 19:38:23',
                'updateUserId': 1,
            },
            {
                'menuName': '新建目录',
                'menuType': 3,
                'parentId': 147,
                'sort': 1,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'support:helpDocCatalog:addCategory',
                'apiPerms': 'support:helpDocCatalog:addCategory',
                'icon': null,
                'contextMenuId': 147,
                'menuId': 170,
                'createTime': '2022-10-16 20:12:57',
                'createUserId': 1,
                'updateTime': '2023-10-07 14:06:38',
                'updateUserId': 1,
            },
            {
                'menuName': '心跳监控',
                'menuType': 2,
                'parentId': 111,
                'sort': 1,
                'path': '/support/heart-beat/heart-beat-list',
                'component': '/support/heart-beat/heart-beat-list.vue',
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': null,
                'apiPerms': null,
                'icon': 'FallOutlined',
                'contextMenuId': null,
                'menuId': 206,
                'createTime': '2022-10-22 10:47:03',
                'createUserId': 1,
                'updateTime': '2022-10-22 18:32:52',
                'updateUserId': 1,
            },
            {
                'menuName': '部门管理',
                'menuType': 2,
                'parentId': 45,
                'sort': 1,
                'path': '/organization/department',
                'component': '/system/department/department-list.vue',
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': null,
                'apiPerms': null,
                'icon': 'ApartmentOutlined',
                'contextMenuId': null,
                'menuId': 219,
                'createTime': '2024-06-22 16:40:21',
                'createUserId': 1,
                'updateTime': '2024-07-02 20:15:17',
                'updateUserId': 1,
            },
            {
                'menuName': '三级等保设置',
                'menuType': 2,
                'parentId': 213,
                'sort': 1,
                'path': '/support/level3protect/level3-protect-config-index',
                'component':
                    '/support/level3protect/level3-protect-config-index.vue',
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': true,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': null,
                'apiPerms': null,
                'icon': 'SafetyOutlined',
                'contextMenuId': null,
                'menuId': 250,
                'createTime': '2024-08-13 11:41:02',
                'createUserId': 44,
                'updateTime': '2024-08-13 11:58:12',
                'updateUserId': 44,
            },
            {
                'menuName': '商品分类',
                'menuType': 2,
                'parentId': 48,
                'sort': 2,
                'path': '/erp/catalog/goods',
                'component': '/business/erp/catalog/goods-catalog.vue',
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': true,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': null,
                'webPerms': null,
                'apiPerms': null,
                'icon': 'ApartmentOutlined',
                'contextMenuId': null,
                'menuId': 78,
                'createTime': '2022-05-18 23:34:14',
                'createUserId': 1,
                'updateTime': '2023-12-01 19:33:13',
                'updateUserId': 1,
            },
            {
                'menuName': '修改部门',
                'menuType': 3,
                'parentId': 46,
                'sort': 2,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'system:department:update',
                'apiPerms': 'system:department:update',
                'icon': null,
                'contextMenuId': null,
                'menuId': 87,
                'createTime': '2022-05-26 23:34:11',
                'createUserId': 1,
                'updateTime': '2023-10-07 18:26:44',
                'updateUserId': 1,
            },
            {
                'menuName': '公告管理',
                'menuType': 2,
                'parentId': 138,
                'sort': 2,
                'path': '/oa/notice/notice-list',
                'component': '/business/oa/notice/notice-list.vue',
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': true,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': null,
                'webPerms': null,
                'apiPerms': null,
                'icon': 'SoundOutlined',
                'contextMenuId': null,
                'menuId': 132,
                'createTime': '2022-06-24 18:23:09',
                'createUserId': 1,
                'updateTime': '2024-07-08 13:58:51',
                'updateUserId': 1,
            },
            {
                'menuName': '意见反馈',
                'menuType': 2,
                'parentId': 218,
                'sort': 2,
                'path': '/feedback/feedback-list',
                'component': '/support/feedback/feedback-list.vue',
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': null,
                'webPerms': null,
                'apiPerms': null,
                'icon': 'CoffeeOutlined',
                'contextMenuId': null,
                'menuId': 148,
                'createTime': '2022-09-14 19:59:52',
                'createUserId': 1,
                'updateTime': '2023-12-01 19:38:40',
                'updateUserId': 1,
            },
            {
                'menuName': '修改目录',
                'menuType': 3,
                'parentId': 147,
                'sort': 2,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'support:helpDocCatalog:update',
                'apiPerms': 'support:helpDocCatalog:update',
                'icon': null,
                'contextMenuId': 147,
                'menuId': 171,
                'createTime': '2022-10-16 20:13:46',
                'createUserId': 1,
                'updateTime': '2023-10-07 14:06:49',
                'updateUserId': 1,
            },
            {
                'menuName': '接口加解密',
                'menuType': 2,
                'parentId': 213,
                'sort': 2,
                'path': '/support/api-encrypt',
                'component': '/support/api-encrypt/api-encrypt-index.vue',
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': true,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': null,
                'apiPerms': null,
                'icon': 'CodepenCircleOutlined',
                'contextMenuId': null,
                'menuId': 215,
                'createTime': '2023-10-24 11:49:28',
                'createUserId': 1,
                'updateTime': '2024-08-13 12:00:14',
                'updateUserId': 44,
            },
            {
                'menuName': '职务管理',
                'menuType': 2,
                'parentId': 45,
                'sort': 2,
                'path': '/organization/position',
                'component': '/system/position/position-list.vue',
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': true,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': null,
                'apiPerms': null,
                'icon': 'ApartmentOutlined',
                'contextMenuId': null,
                'menuId': 228,
                'createTime': '2024-06-29 11:11:09',
                'createUserId': 1,
                'updateTime': '2024-07-02 20:15:11',
                'updateUserId': 1,
            },
            {
                'menuName': '组织架构',
                'menuType': 1,
                'parentId': 0,
                'sort': 3,
                'path': '/organization',
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': null,
                'webPerms': null,
                'apiPerms': null,
                'icon': 'UserSwitchOutlined',
                'contextMenuId': null,
                'menuId': 45,
                'createTime': '2021-08-12 16:13:27',
                'createUserId': 1,
                'updateTime': '2024-07-02 19:27:44',
                'updateUserId': 1,
            },
            {
                'menuName': '员工管理',
                'menuType': 2,
                'parentId': 45,
                'sort': 3,
                'path': '/organization/employee',
                'component': '/system/employee/index.vue',
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': null,
                'webPerms': null,
                'apiPerms': null,
                'icon': 'AuditOutlined',
                'contextMenuId': null,
                'menuId': 46,
                'createTime': '2021-08-12 16:21:50',
                'createUserId': 1,
                'updateTime': '2024-07-02 20:15:23',
                'updateUserId': 1,
            },
            {
                'menuName': '商品管理',
                'menuType': 1,
                'parentId': 138,
                'sort': 3,
                'path': '/goods',
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': null,
                'webPerms': null,
                'apiPerms': null,
                'icon': 'BarcodeOutlined',
                'contextMenuId': null,
                'menuId': 48,
                'createTime': '2021-08-12 18:02:59',
                'createUserId': 1,
                'updateTime': '2024-07-08 13:58:46',
                'updateUserId': 1,
            },
            {
                'menuName': '自定义分组',
                'menuType': 2,
                'parentId': 48,
                'sort': 3,
                'path': '/erp/catalog/custom',
                'component': '/business/erp/catalog/custom-catalog.vue',
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': null,
                'webPerms': null,
                'apiPerms': null,
                'icon': 'AppstoreAddOutlined',
                'contextMenuId': null,
                'menuId': 79,
                'createTime': '2022-05-18 23:37:53',
                'createUserId': 1,
                'updateTime': '2023-12-01 19:33:16',
                'updateUserId': 1,
            },
            {
                'menuName': '删除部门',
                'menuType': 3,
                'parentId': 46,
                'sort': 3,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'system:department:delete',
                'apiPerms': 'system:department:delete',
                'icon': null,
                'contextMenuId': null,
                'menuId': 88,
                'createTime': '2022-05-26 23:34:49',
                'createUserId': 1,
                'updateTime': '2023-10-07 18:26:49',
                'updateUserId': 1,
            },
            {
                'menuName': '参数配置',
                'menuType': 2,
                'parentId': 50,
                'sort': 3,
                'path': '/config/config-list',
                'component': '/support/config/config-list.vue',
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': null,
                'webPerms': null,
                'apiPerms': null,
                'icon': 'AntDesignOutlined',
                'contextMenuId': null,
                'menuId': 109,
                'createTime': '2022-05-27 13:34:41',
                'createUserId': 1,
                'updateTime': '2022-06-23 16:24:16',
                'updateUserId': 1,
            },
            {
                'menuName': '更新日志',
                'menuType': 2,
                'parentId': 218,
                'sort': 3,
                'path': '/support/change-log/change-log-list',
                'component': '/support/change-log/change-log-list.vue',
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': null,
                'webPerms': null,
                'apiPerms': null,
                'icon': 'HeartOutlined',
                'contextMenuId': null,
                'menuId': 152,
                'createTime': '2022-10-10 10:31:20',
                'createUserId': 44,
                'updateTime': '2023-12-01 19:38:51',
                'updateUserId': 1,
            },
            {
                'menuName': '导入',
                'menuType': 3,
                'parentId': 47,
                'sort': 3,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': true,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'goods:importGoods',
                'apiPerms': 'goods:importGoods',
                'icon': null,
                'contextMenuId': null,
                'menuId': 217,
                'createTime': '2023-12-01 19:34:22',
                'createUserId': 1,
                'updateTime': '2023-12-01 19:34:22',
                'updateUserId': null,
            },
            {
                'menuName': '敏感数据脱敏',
                'menuType': 2,
                'parentId': 213,
                'sort': 3,
                'path': '/support/level3protect/data-masking-list',
                'component': '/support/level3protect/data-masking-list.vue',
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': true,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': null,
                'apiPerms': null,
                'icon': 'FileProtectOutlined',
                'contextMenuId': null,
                'menuId': 251,
                'createTime': '2024-08-13 11:58:00',
                'createUserId': 44,
                'updateTime': '2024-08-13 11:59:49',
                'updateUserId': 44,
            },
            {
                'menuName': '角色管理',
                'menuType': 2,
                'parentId': 45,
                'sort': 4,
                'path': '/organization/role',
                'component': '/system/role/index.vue',
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': null,
                'webPerms': null,
                'apiPerms': null,
                'icon': 'SlidersOutlined',
                'contextMenuId': null,
                'menuId': 76,
                'createTime': '2021-08-26 10:31:00',
                'createUserId': 1,
                'updateTime': '2024-07-02 20:15:28',
                'updateUserId': 1,
            },
            {
                'menuName': '数据字典',
                'menuType': 2,
                'parentId': 50,
                'sort': 4,
                'path': '/setting/dict',
                'component': '/support/dict/index.vue',
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': null,
                'webPerms': null,
                'apiPerms': null,
                'icon': 'BarcodeOutlined',
                'contextMenuId': null,
                'menuId': 110,
                'createTime': '2022-05-27 17:53:00',
                'createUserId': 1,
                'updateTime': '2022-05-27 18:09:14',
                'updateUserId': 1,
            },
            {
                'menuName': '数据库监控',
                'menuType': 2,
                'parentId': 111,
                'sort': 4,
                'path': '/support/druid/index',
                'component': null,
                'frameFlag': true,
                'frameUrl': 'http://localhost:1024/druid',
                'cacheFlag': true,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': null,
                'webPerms': null,
                'apiPerms': null,
                'icon': 'ConsoleSqlOutlined',
                'contextMenuId': null,
                'menuId': 122,
                'createTime': '2022-06-20 14:49:33',
                'createUserId': 1,
                'updateTime': '2023-02-16 19:15:58',
                'updateUserId': 1,
            },
            {
                'menuName': '登录失败锁定',
                'menuType': 2,
                'parentId': 213,
                'sort': 4,
                'path': '/support/login-fail',
                'component': '/support/login-fail/login-fail-list.vue',
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': true,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': null,
                'apiPerms': null,
                'icon': 'LockOutlined',
                'contextMenuId': null,
                'menuId': 214,
                'createTime': '2023-10-17 19:04:24',
                'createUserId': 1,
                'updateTime': '2024-08-13 14:16:26',
                'updateUserId': 44,
            },
            {
                'menuName': '文档中心',
                'menuType': 1,
                'parentId': 0,
                'sort': 4,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': true,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': null,
                'apiPerms': null,
                'icon': 'FileSearchOutlined',
                'contextMenuId': null,
                'menuId': 218,
                'createTime': '2023-12-01 19:37:28',
                'createUserId': 1,
                'updateTime': '2023-12-01 19:37:51',
                'updateUserId': 1,
            },
            {
                'menuName': 'knife4j文档',
                'menuType': 2,
                'parentId': 218,
                'sort': 4,
                'path': '/knife4j',
                'component': null,
                'frameFlag': true,
                'frameUrl': 'http://localhost:1024/doc.html',
                'cacheFlag': true,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': null,
                'apiPerms': null,
                'icon': 'FileWordOutlined',
                'contextMenuId': null,
                'menuId': 233,
                'createTime': '2024-07-02 20:23:50',
                'createUserId': 1,
                'updateTime': '2024-07-08 13:49:15',
                'updateUserId': 1,
            },
            {
                'menuName': '登录登出记录',
                'menuType': 2,
                'parentId': 213,
                'sort': 5,
                'path': '/support/login-log/login-log-list',
                'component': '/support/login-log/login-log-list.vue',
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': null,
                'webPerms': null,
                'apiPerms': null,
                'icon': 'LoginOutlined',
                'contextMenuId': null,
                'menuId': 143,
                'createTime': '2022-06-28 15:01:38',
                'createUserId': 1,
                'updateTime': '2024-08-13 14:33:49',
                'updateUserId': 44,
            },
            {
                'menuName': '网络安全',
                'menuType': 1,
                'parentId': 0,
                'sort': 5,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': true,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': null,
                'apiPerms': null,
                'icon': 'SafetyCertificateOutlined',
                'contextMenuId': null,
                'menuId': 213,
                'createTime': '2023-10-17 19:03:08',
                'createUserId': 1,
                'updateTime': '2023-12-01 19:38:00',
                'updateUserId': 1,
            },
            {
                'menuName': 'swagger文档',
                'menuType': 2,
                'parentId': 218,
                'sort': 5,
                'path': '/swagger',
                'component': 'http://localhost:1024/swagger-ui/index.html',
                'frameFlag': true,
                'frameUrl': 'http://localhost:1024/swagger-ui/index.html',
                'cacheFlag': true,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': null,
                'apiPerms': null,
                'icon': 'ApiOutlined',
                'contextMenuId': null,
                'menuId': 234,
                'createTime': '2024-07-02 20:35:43',
                'createUserId': 1,
                'updateTime': '2024-07-08 13:49:26',
                'updateUserId': 1,
            },
            {
                'menuName': '系统设置',
                'menuType': 1,
                'parentId': 0,
                'sort': 6,
                'path': '/setting',
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': null,
                'webPerms': null,
                'apiPerms': null,
                'icon': 'SettingOutlined',
                'contextMenuId': null,
                'menuId': 50,
                'createTime': '2021-08-13 16:41:33',
                'createUserId': 1,
                'updateTime': '2023-12-01 19:38:03',
                'updateUserId': 1,
            },
            {
                'menuName': '用户操作记录',
                'menuType': 2,
                'parentId': 213,
                'sort': 6,
                'path': '/support/operate-log/operate-log-list',
                'component': '/support/operate-log/operate-log-list.vue',
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': null,
                'webPerms': null,
                'apiPerms': null,
                'icon': 'VideoCameraOutlined',
                'contextMenuId': null,
                'menuId': 81,
                'createTime': '2022-05-20 12:37:24',
                'createUserId': 1,
                'updateTime': '2024-08-13 14:34:10',
                'updateUserId': 44,
            },
            {
                'menuName': '单号管理',
                'menuType': 2,
                'parentId': 50,
                'sort': 6,
                'path': '/support/serial-number/serial-number-list',
                'component': '/support/serial-number/serial-number-list.vue',
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': null,
                'webPerms': null,
                'apiPerms': null,
                'icon': 'NumberOutlined',
                'contextMenuId': null,
                'menuId': 130,
                'createTime': '2022-06-24 14:45:22',
                'createUserId': 1,
                'updateTime': '2022-06-28 16:23:41',
                'updateUserId': 1,
            },
            {
                'menuName': '缓存管理',
                'menuType': 2,
                'parentId': 50,
                'sort': 11,
                'path': '/support/cache/cache-list',
                'component': '/support/cache/cache-list.vue',
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': null,
                'webPerms': null,
                'apiPerms': null,
                'icon': 'BorderInnerOutlined',
                'contextMenuId': null,
                'menuId': 133,
                'createTime': '2022-06-24 18:52:25',
                'createUserId': 1,
                'updateTime': '2023-12-01 19:39:13',
                'updateUserId': 1,
            },
            {
                'menuName': '查询',
                'menuType': 3,
                'parentId': 147,
                'sort': 11,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'support:helpDoc:query',
                'apiPerms': 'support:helpDoc:query',
                'icon': null,
                'contextMenuId': 147,
                'menuId': 168,
                'createTime': '2022-10-16 20:12:13',
                'createUserId': 1,
                'updateTime': '2023-10-07 14:05:49',
                'updateUserId': 1,
            },
            {
                'menuName': 'Reload',
                'menuType': 2,
                'parentId': 50,
                'sort': 12,
                'path': '/hook',
                'component': '/support/reload/reload-list.vue',
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': null,
                'webPerms': null,
                'apiPerms': null,
                'icon': 'ReloadOutlined',
                'contextMenuId': null,
                'menuId': 117,
                'createTime': '2022-06-20 10:16:49',
                'createUserId': 1,
                'updateTime': '2023-12-01 19:39:17',
                'updateUserId': 1,
            },
            {
                'menuName': '新建',
                'menuType': 3,
                'parentId': 147,
                'sort': 12,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'support:helpDoc:add',
                'apiPerms': 'support:helpDoc:add',
                'icon': null,
                'contextMenuId': 147,
                'menuId': 169,
                'createTime': '2022-10-16 20:12:37',
                'createUserId': 1,
                'updateTime': '2023-10-07 14:05:56',
                'updateUserId': 1,
            },
            {
                'menuName': '更新',
                'menuType': 3,
                'parentId': 147,
                'sort': 13,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'support:helpDoc:update',
                'apiPerms': 'support:helpDoc:update',
                'icon': null,
                'contextMenuId': null,
                'menuId': 202,
                'createTime': '2022-10-21 21:03:32',
                'createUserId': 1,
                'updateTime': '2023-10-07 14:06:56',
                'updateUserId': 1,
            },
            {
                'menuName': '删除',
                'menuType': 3,
                'parentId': 147,
                'sort': 14,
                'path': null,
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': 'support:helpDoc:delete',
                'apiPerms': 'support:helpDoc:delete',
                'icon': null,
                'contextMenuId': null,
                'menuId': 201,
                'createTime': '2022-10-21 21:03:20',
                'createUserId': 1,
                'updateTime': '2023-10-07 14:07:02',
                'updateUserId': 1,
            },
            {
                'menuName': '文件管理',
                'menuType': 2,
                'parentId': 50,
                'sort': 20,
                'path': '/support/file/file-list',
                'component': '/support/file/file-list.vue',
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': null,
                'webPerms': null,
                'apiPerms': null,
                'icon': 'FolderOpenOutlined',
                'contextMenuId': null,
                'menuId': 193,
                'createTime': '2022-10-21 11:26:11',
                'createUserId': 1,
                'updateTime': '2022-10-22 11:29:22',
                'updateUserId': 1,
            },
            {
                'menuName': '定时任务',
                'menuType': 2,
                'parentId': 50,
                'sort': 25,
                'path': '/job/list',
                'component': '/support/job/job-list.vue',
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': true,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': 1,
                'webPerms': null,
                'apiPerms': null,
                'icon': 'AppstoreOutlined',
                'contextMenuId': null,
                'menuId': 221,
                'createTime': '2024-06-25 17:57:40',
                'createUserId': 2,
                'updateTime': '2024-06-25 19:49:21',
                'updateUserId': 2,
            },
            {
                'menuName': '监控服务',
                'menuType': 1,
                'parentId': 0,
                'sort': 100,
                'path': '/monitor',
                'component': null,
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': null,
                'webPerms': null,
                'apiPerms': null,
                'icon': 'BarChartOutlined',
                'contextMenuId': null,
                'menuId': 111,
                'createTime': '2022-06-17 11:13:23',
                'createUserId': 1,
                'updateTime': '2023-11-28 17:43:56',
                'updateUserId': 1,
            },
            {
                'menuName': '代码生成',
                'menuType': 2,
                'parentId': 0,
                'sort': 600,
                'path': '/support/code-generator',
                'component': '/support/code-generator/code-generator-list.vue',
                'frameFlag': false,
                'frameUrl': null,
                'cacheFlag': false,
                'visibleFlag': true,
                'disabledFlag': false,
                'permsType': null,
                'webPerms': null,
                'apiPerms': null,
                'icon': 'CoffeeOutlined',
                'contextMenuId': null,
                'menuId': 151,
                'createTime': '2022-09-21 18:25:05',
                'createUserId': 1,
                'updateTime': '2022-10-22 11:27:58',
                'updateUserId': 1,
            },
        ],
        'needUpdatePwdFlag': false,
        'lastLoginIp': null,
        'lastLoginIpRegion': null,
        'lastLoginUserAgent': null,
        'lastLoginTime': null,
        'userName': '管理员',
        'userId': 1,
    },
    'dataType': 1,
}
